package dbx_test

import dbx "github.com/DaiYuANg/arcgo/dbx"

type Aggregate[T any] = dbx.Aggregate[T]
type Assignment = dbx.Assignment
type AtlasCompiledSchemaTestView = dbx.AtlasCompiledSchemaTestView
type BelongsTo[E any, T any] = dbx.BelongsTo[E, T]
type BoundQuery = dbx.BoundQuery
type CaseBuilder[T any] = dbx.CaseBuilder[T]
type Check[E any] = dbx.Check[E]
type CheckMeta = dbx.CheckMeta
type CheckState = dbx.CheckState
type Codec = dbx.Codec
type Column[E any, T any] = dbx.Column[E, T]
type ColumnMeta = dbx.ColumnMeta
type ColumnState = dbx.ColumnState
type CompositeKey[E any] = dbx.CompositeKey[E]
type Cursor[T any] = dbx.Cursor[T]
type DB = dbx.DB
type DeleteQuery = dbx.DeleteQuery
type Executor = dbx.Executor
type ForeignKeyMeta = dbx.ForeignKeyMeta
type ForeignKeyState = dbx.ForeignKeyState
type HasMany[E any, T any] = dbx.HasMany[E, T]
type HasOne[E any, T any] = dbx.HasOne[E, T]
type Hook = dbx.Hook
type HookEvent = dbx.HookEvent
type HookFuncs = dbx.HookFuncs
type IDGenerator = dbx.IDGenerator
type IDColumn[E any, T any, M dbx.IDMarker] = dbx.IDColumn[E, T, M]
type IDKSUID = dbx.IDKSUID
type IDSnowflake = dbx.IDSnowflake
type IDULID = dbx.IDULID
type IDUUID = dbx.IDUUID
type IDUUIDv4 = dbx.IDUUIDv4
type IDUUIDv7 = dbx.IDUUIDv7
type Index[E any] = dbx.Index[E]
type IndexMeta = dbx.IndexMeta
type IndexState = dbx.IndexState
type InsertQuery = dbx.InsertQuery
type MappedField = dbx.MappedField
type ManyToMany[E any, T any] = dbx.ManyToMany[E, T]
type Mapper[E any] = dbx.Mapper[E]
type MapperOption = dbx.MapperOption
type MigrationAction = dbx.MigrationAction
type MigrationPlan = dbx.MigrationPlan
type NodeIDOutOfRangeError = dbx.NodeIDOutOfRangeError
type Operation = dbx.Operation
type Option = dbx.Option
type Predicate = dbx.Predicate
type PrimaryKeyMeta = dbx.PrimaryKeyMeta
type PrimaryKeyState = dbx.PrimaryKeyState
type PrimaryKeyUnmappedError = dbx.PrimaryKeyUnmappedError
type QueryBuilder = dbx.QueryBuilder
type ReferentialAction = dbx.ReferentialAction
type RelationKind = dbx.RelationKind
type Row = dbx.Row
type RowsScanner[E any] = dbx.RowsScanner[E]
type Schema[E any] = dbx.Schema[E]
type SchemaDriftError = dbx.SchemaDriftError
type SchemaResource = dbx.SchemaResource
type SchemaSource[E any] = dbx.SchemaSource[E]
type SelectItem = dbx.SelectItem
type SelectQuery = dbx.SelectQuery
type Session = dbx.Session
type SQLExecutor = dbx.SQLExecutor
type SQLStatement = dbx.SQLStatement
type SQLStatementSource = dbx.SQLStatementSource
type StructMapper[E any] = dbx.StructMapper[E]
type Table = dbx.Table
type TableSource = dbx.TableSource
type TableSpec = dbx.TableSpec
type TableState = dbx.TableState
type UnknownCodecError = dbx.UnknownCodecError
type UnmappedColumnError = dbx.UnmappedColumnError
type ValidationBackend = dbx.ValidationBackend
type ValidationReport = dbx.ValidationReport

const (
	DefaultNodeID              = dbx.DefaultNodeID
	DefaultUUIDVersion         = dbx.DefaultUUIDVersion
	IDStrategyDBAuto           = dbx.IDStrategyDBAuto
	IDStrategySnowflake        = dbx.IDStrategySnowflake
	IDStrategyUUID             = dbx.IDStrategyUUID
	MigrationActionCreateIndex = dbx.MigrationActionCreateIndex
	MigrationActionCreateTable = dbx.MigrationActionCreateTable
	MigrationActionManual      = dbx.MigrationActionManual
	OperationAutoMigrate       = dbx.OperationAutoMigrate
	OperationBeginTx           = dbx.OperationBeginTx
	OperationCommitTx          = dbx.OperationCommitTx
	OperationExec              = dbx.OperationExec
	OperationQuery             = dbx.OperationQuery
	OperationQueryRow          = dbx.OperationQueryRow
	OperationRollbackTx        = dbx.OperationRollbackTx
	OperationValidate          = dbx.OperationValidate
	ReferentialCascade         = dbx.ReferentialCascade
	RelationBelongsTo          = dbx.RelationBelongsTo
	RelationManyToMany         = dbx.RelationManyToMany
	ValidationBackendLegacy    = dbx.ValidationBackendLegacy
)
