package postgres

import (
	"context"
	"database/sql/driver"
	"reflect"
	"testing"

	"github.com/DaiYuANg/arcgo/dbx"
	"github.com/DaiYuANg/arcgo/dbx/internal/testsql"
)

func TestBuildCreateTable(t *testing.T) {
	bound, err := Dialect{}.BuildCreateTable(dbx.TableSpec{
		Name:        "users",
		Columns:     []dbx.ColumnMeta{{Name: "id", Table: "users", GoType: reflect.TypeFor[int64](), PrimaryKey: true, AutoIncrement: true}, {Name: "username", Table: "users", GoType: reflect.TypeFor[string]()}, {Name: "email_address", Table: "users", GoType: reflect.TypeFor[string]()}, {Name: "role_id", Table: "users", GoType: reflect.TypeFor[int64]()}, {Name: "status", Table: "users", GoType: reflect.TypeFor[int]()}},
		PrimaryKey:  &dbx.PrimaryKeyMeta{Name: "pk_users", Table: "users", Columns: []string{"id"}},
		ForeignKeys: []dbx.ForeignKeyMeta{{Name: "fk_users_role_id", Table: "users", Columns: []string{"role_id"}, TargetTable: "roles", TargetColumns: []string{"id"}, OnDelete: dbx.ReferentialCascade}},
		Checks:      []dbx.CheckMeta{{Name: "ck_users_status", Table: "users", Expression: "status >= 0"}},
	})
	if err != nil {
		t.Fatalf("BuildCreateTable returned error: %v", err)
	}
	expected := `CREATE TABLE IF NOT EXISTS "users" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "username" TEXT NOT NULL, "email_address" TEXT NOT NULL, "role_id" BIGINT NOT NULL, "status" INTEGER NOT NULL, CONSTRAINT "fk_users_role_id" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON DELETE CASCADE, CONSTRAINT "ck_users_status" CHECK (status >= 0))`
	if bound.SQL != expected {
		t.Fatalf("unexpected create sql:\nwant: %s\n got: %s", expected, bound.SQL)
	}
}

func TestInspectTable(t *testing.T) {
	sqlDB, _, cleanup, err := testsql.Open(testsql.Plan{Queries: []testsql.QueryPlan{
		{SQL: "SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = $1)", Args: []driver.Value{"users"}, Columns: []string{"exists"}, Rows: [][]driver.Value{{true}}},
		{SQL: "SELECT tc.constraint_name, kcu.column_name FROM information_schema.table_constraints tc JOIN information_schema.key_column_usage kcu ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema AND tc.table_name = kcu.table_name WHERE tc.table_schema = current_schema() AND tc.table_name = $1 AND tc.constraint_type = 'PRIMARY KEY' ORDER BY kcu.ordinal_position", Args: []driver.Value{"users"}, Columns: []string{"constraint_name", "column_name"}, Rows: [][]driver.Value{{"pk_users", "id"}}},
		{SQL: "SELECT c.column_name, c.udt_name, c.is_nullable, c.column_default, (c.is_identity = 'YES') AS is_identity FROM information_schema.columns c WHERE c.table_schema = current_schema() AND c.table_name = $1 ORDER BY c.ordinal_position", Args: []driver.Value{"users"}, Columns: []string{"column_name", "udt_name", "is_nullable", "column_default", "is_identity"}, Rows: [][]driver.Value{{"id", "int8", "NO", nil, true}, {"username", "text", "NO", nil, false}, {"email_address", "text", "NO", nil, false}, {"role_id", "int8", "NO", nil, false}, {"status", "int4", "NO", nil, false}}},
		{SQL: "SELECT indexname, indexdef FROM pg_indexes WHERE schemaname = current_schema() AND tablename = $1", Args: []driver.Value{"users"}, Columns: []string{"indexname", "indexdef"}, Rows: [][]driver.Value{{"idx_users_username", "CREATE INDEX idx_users_username ON public.users USING btree (username)"}, {"ux_users_email_address", "CREATE UNIQUE INDEX ux_users_email_address ON public.users USING btree (email_address)"}}},
		{SQL: "SELECT tc.constraint_name, kcu.column_name, ccu.table_name, ccu.column_name, rc.update_rule, rc.delete_rule FROM information_schema.table_constraints tc JOIN information_schema.key_column_usage kcu ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema AND tc.table_name = kcu.table_name JOIN information_schema.constraint_column_usage ccu ON tc.constraint_name = ccu.constraint_name AND tc.table_schema = ccu.table_schema JOIN information_schema.referential_constraints rc ON tc.constraint_name = rc.constraint_name AND tc.table_schema = rc.constraint_schema WHERE tc.table_schema = current_schema() AND tc.table_name = $1 AND tc.constraint_type = 'FOREIGN KEY' ORDER BY tc.constraint_name, kcu.ordinal_position", Args: []driver.Value{"users"}, Columns: []string{"constraint_name", "column_name", "table_name", "column_name", "update_rule", "delete_rule"}, Rows: [][]driver.Value{{"fk_users_role_id", "role_id", "roles", "id", "NO ACTION", "CASCADE"}}},
		{SQL: "SELECT tc.constraint_name, cc.check_clause FROM information_schema.table_constraints tc JOIN information_schema.check_constraints cc ON tc.constraint_name = cc.constraint_name AND tc.table_schema = cc.constraint_schema WHERE tc.table_schema = current_schema() AND tc.table_name = $1 AND tc.constraint_type = 'CHECK' ORDER BY tc.constraint_name", Args: []driver.Value{"users"}, Columns: []string{"constraint_name", "check_clause"}, Rows: [][]driver.Value{{"ck_users_status", "status >= 0"}}},
	}})
	if err != nil {
		t.Fatalf("testsql.Open returned error: %v", err)
	}
	defer cleanup()

	state, err := Dialect{}.InspectTable(context.Background(), sqlDB, "users")
	if err != nil {
		t.Fatalf("InspectTable returned error: %v", err)
	}
	if !state.Exists || len(state.Columns) != 5 || len(state.Indexes) != 2 {
		t.Fatalf("unexpected table state: %+v", state)
	}
	if state.PrimaryKey == nil || state.PrimaryKey.Name != "pk_users" {
		t.Fatalf("unexpected primary key state: %+v", state.PrimaryKey)
	}
	if len(state.ForeignKeys) != 1 || state.ForeignKeys[0].TargetTable != "roles" {
		t.Fatalf("unexpected foreign key state: %+v", state.ForeignKeys)
	}
	if len(state.Checks) != 1 || state.Checks[0].Expression != "status >= 0" {
		t.Fatalf("unexpected check state: %+v", state.Checks)
	}
}
