# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  default:
    desc: server
    cmds:
      - go tool hugo server --buildDrafts --disableFastRender
    silent: true
